const playlists = ["싸이월드 플레이리스트", "CM 추천"];

export const musicData = [
  {
    videoId: "dYIT_jeUBKg",
    artist: "프리스타일",
    title: "Y",
    time: "4:41",
    playlists: [playlists[0]],
  },
  {
    videoId: "NIPtyAKxlRs",
    artist: "에픽하이",
    title: "우산 (Feat.윤하)",
    time: "4:56",
    playlists: [playlists[0]],
  },
  {
    videoId: "xpHJnmp3Lyw",
    artist: "Gavy NJ",
    title: "해바라기",
    time: "3:41",
    playlists: [playlists[0]],
  },

  {
    videoId: "eOqSUto9Z1g",
    artist: "Sweetbox",
    title: "Life Is Cool",
    time: "2:57",
    playlists: [playlists[0]],
  },
  {
    videoId: "POApmDGm8r8",
    artist: "MC 스나이퍼",
    title: "마법의 성",
    time: "4:40",
    playlists: [playlists[0]],
  },
  {
    videoId: "ppjRIEgcXIY",
    artist: "다이나믹 듀오",
    title: "죽일놈",
    time: "3:43",
    playlists: [playlists[0]],
  },
  {
    videoId: "_TOu_1zVCUk",
    artist: "리쌍",
    title: "헤어지지 못하는 여자, 떠나가지 못하는 남자 (Feat. 정인)",
    time: "4:44",
    playlists: [playlists[0]],
  },
  {
    videoId: "uNgg_uBYZkw",
    artist: "Brown Eyed Girls",
    title: "LOVE",
    time: "3:39",
    playlists: [playlists[0]],
  },
  {
    videoId: "VUhGP9sqKdw",
    artist: "원투",
    title: "못된여자 (Feat. 서인영)",
    time: "3:41",
    playlists: [playlists[0]],
  },
  {
    videoId: "z5_HPxLJBf0",
    artist: "원투",
    title: "못된여자2 (Feat. 서인영)",
    time: "3:56",
    playlists: [playlists[0]],
  },
  {
    videoId: "bv1PxDNQ6bo",
    artist: "허밍 어반 스테레오",
    title: "Hawaiian Couple",
    time: "3:42",
    playlists: [playlists[0]],
  },
  {
    videoId: "faPQoNUC4GQ",
    artist: "자두",
    title: "대화가 필요해",
    time: "3:58",
    playlists: [playlists[0]],
  },
  {
    videoId: "v3SaQZypZ_U",
    artist: "하울, 제이",
    title: "사랑인가요 (궁 OST)",
    time: "4:37",
    playlists: [playlists[0]],
  },
  {
    videoId: "4mDOG3PAjao",
    artist: "샵",
    title: "내 입술... 따뜻한 커피처럼",
    time: "3:46",
    playlists: [playlists[0]],
  },
  {
    videoId: "iaDgfQ0sIYY",
    artist: "싸이",
    title: "낙원 (Feat. 이재훈)",
    time: "3:42",
    playlists: [playlists[0]],
  },
  {
    videoId: "Cbg6nJulpEQ",
    artist: "이지라이프",
    title: "너말고 니언니",
    time: "3:43",
    playlists: [playlists[0]],
  },
  {
    videoId: "oF7C6GuMD5g",
    artist: "Brown Eyed Girls",
    title: "Hold The Line (Feat. 조PD)",
    time: "4:03",
    playlists: [playlists[0]],
  },
  {
    videoId: "c9sEdAo39gk",
    artist: "언터쳐블",
    title: "가슴에 살아 (Feat. 나르샤)",
    time: "3:49",
    playlists: [playlists[0]],
  },
  {
    videoId: "c7KXtINADRo",
    artist: "박해경",
    title: "Lemon Tree",
    time: "3:17",
    playlists: [playlists[0]],
  },
  {
    videoId: "sGD75Kncck8",
    artist: "PK헤만",
    title: "Evergreen (Feat. 이지혜)",
    time: "3:16",
    playlists: [playlists[0]],
  },
  {
    videoId: "fuCmW_1_wxs",
    artist: "더 넛츠",
    title: "사랑의 바보",
    time: "4:21",
    playlists: [playlists[0]],
  },
  {
    videoId: "98Q2p-3kMDI",
    artist: "izi",
    title: "응급실",
    time: "3:44",
    playlists: [playlists[0]],
  },
  {
    videoId: "fuFJqIfnB5o",
    artist: "버즈",
    title: "사랑은 가슴이 시킨다",
    time: "4:20",
    playlists: [playlists[0]],
  },
  {
    videoId: "2lODuVyCcgU",
    artist: "에이트",
    title: "잘가요 내사랑",
    time: "3:46",
    playlists: [playlists[0]],
  },
  {
    videoId: "zgvI5Jqph08",
    artist: "양정승",
    title: "밤하늘의 별을 (With. KCM & No Noo)",
    time: "3:44",
    playlists: [playlists[0]],
  },
  {
    videoId: "h0cj_A0np-M",
    artist: "버즈",
    title: "은인",
    time: "4:26",
    playlists: [playlists[0]],
  },
  {
    videoId: "_6C5-abCx6g",
    artist: "윤하",
    title: "기다리다",
    time: "4:37",
    playlists: [playlists[0]],
  },
  {
    videoId: "-VP7fUqTWYY",
    artist: "태연",
    title: "들리나요",
    time: "4:00",
    playlists: [playlists[0]],
  },
  {
    videoId: "2WyOq7IMEnc",
    artist: "이보람",
    title: "처음 그 자리에",
    time: "3:53",
    playlists: [playlists[0]],
  },
  {
    videoId: "oo0ESiTp6VM",
    artist: "유미",
    title: "별",
    time: "5:01",
    playlists: [playlists[0]],
  },
  {
    videoId: "qmlUuTvKUpU",
    artist: "러브홀릭",
    title: "인형의 꿈",
    time: "4:38",
    playlists: [playlists[0]],
  },
  {
    videoId: "acdAWdnSKmE",
    artist: "럼블피쉬",
    title: "비와 당신",
    time: "4:09",
    playlists: [playlists[0]],
  },
  {
    videoId: "1RvuFAWlkdo",
    artist: "god",
    title: "길",
    time: "3:46",
    playlists: [playlists[0]],
  },
  {
    videoId: "yPqI1VAHX8Q",
    artist: "모세",
    title: "사랑인걸",
    time: "4:16",
    playlists: [playlists[0]],
  },
  {
    videoId: "JRF7F2E96uw",
    artist: "김형중",
    title: "그랬나봐",
    time: "4:31",
    playlists: [playlists[0]],
  },
  {
    videoId: "oQjzTVCIK5A",
    artist: "쿨",
    title: "아로하",
    time: "4:26",
    playlists: [playlists[0]],
  },
  {
    videoId: "0lgNwO6eUpY",
    artist: "Brown Eyed Soul",
    title: "My Story",
    time: "4:38",
    playlists: [playlists[0]],
  },
  {
    videoId: "G6pMhSdv8Fg",
    artist: "테이",
    title: "같은 배게...",
    time: "4:25",
    playlists: [playlists[0]],
  },
  {
    videoId: "q5mPn6__Brk",
    artist: "이기찬",
    title: "미인",
    time: "3:38",
    playlists: [playlists[0]],
  },
  {
    videoId: "nD1p_H3qo_A",
    artist: "성시경",
    title: "희재",
    time: "4:41",
    playlists: [playlists[0]],
  },
  {
    videoId: "gt7kce8hgSs",
    artist: "지아",
    title: "술 한잔 해요",
    time: "3:30",
    playlists: [playlists[0]],
  },
  {
    videoId: "rTLzLm1ztQY",
    artist: "테이",
    title: "사랑은...향기를 남기고",
    time: "4:57",
    playlists: [playlists[0]],
  },

  {
    videoId: "sVbpvsrtTzM",
    artist: "크리스포터 X 청하",
    title: "When I Get Old",
    time: "3:04",
    playlists: [playlists[1]],
  },
];

const ex = {
  videoId: "",
  artist: "",
  title: "",
  time: "",
  playlists: [playlists[0]],
};
