export const playlists = [
  "음악 전체 보기", // playlists[0]
  "싸이월드 감성", // playlists[1]
  "감성 & 느낌", // playlists[2]
  "텐션 올려!!", // playlists[3]
  "노동요~", // playlists[4]
  "비오는 날..", // playlists[5]
  "Before 2024 Pick", // playlists[6]
  "2024 Pick", // playlists[7]
];

export const musicData = [
  // {
  //   videoId: "",
  //   artist: "",
  //   title: "",
  //   playlists: [playlists[7]],
  // },
  {
    videoId: "NuB-1myGido",
    artist: "The Glitch Mob & Mako & The Word Alive",
    title: "Rise",
    playlists: [playlists[4]],
  },
  {
    videoId: "3dm_5qWWDV8",
    artist: "Muse",
    title: "Hysteria",
    playlists: [playlists[3]],
  },
  {
    videoId: "Ytt37ul4xdg",
    artist: "City Wolf",
    title: "Face In The Dark (feat. Panther)",
    playlists: [playlists[3]],
  },
  {
    videoId: "oJDsJ4z-YAQ",
    artist: "Fall Out Boy",
    title: "The phoenix",
    playlists: [playlists[3]],
  },
  {
    videoId: "YJVmu6yttiw",
    artist: "Skrillex",
    title: "Bangarang (feat. Sirah)",
    playlists: [playlists[3]],
  },
  {
    videoId: "TBD3WRO7Iy8",
    artist: "bbno$",
    title: "Rich Brian",
    playlists: [playlists[3]],
  },
  {
    videoId: "HIgvP7B3Hg8",
    artist: "Bruno Mars",
    title: "Runaway Baby",
    playlists: [playlists[3]],
  },
  {
    videoId: "vqkB7AKERz8",
    artist: "NMIX",
    title: "DASH",
    playlists: [playlists[4], playlists[7]],
  },
  {
    videoId: "jf0_fwHYAbE",
    artist: "청하",
    title: "I'm Ready",
    playlists: [playlists[4], playlists[7]],
  },
  {
    videoId: "K7J_0DDw2RU",
    artist: "SG워너비",
    title: "죄와 벌",
    playlists: [playlists[6]],
  },
  {
    videoId: "MfZWh2bYYeE",
    artist: "가비엔제이",
    title: "Happiness",
    playlists: [playlists[6]],
  },
  {
    videoId: "NkEGzMyAqo",
    artist: "먼데이 키즈",
    title: "Bye Bye Bye",
    playlists: [playlists[6]],
  },
  {
    videoId: "VO88htcm09E",
    artist: "SG워너비",
    title: "광",
    playlists: [playlists[6]],
  },
  {
    videoId: "dJRkhdWsu_M",
    artist: "긱스",
    title: "Officially Missing You",
    playlists: [playlists[6]],
  },
  {
    videoId: "jjuB0S2460Q",
    artist: "버즈",
    title: "남자를 몰라",
    playlists: [playlists[6]],
  },
  {
    videoId: "-kq2oHzgjLc",
    artist: "Brown Eyed Girls",
    title: "다가와서",
    playlists: [playlists[6]],
  },
  {
    videoId: "aIC-b2SrH7U",
    artist: "임정희",
    title:
      "사랑에 미치면 (feat. 아웃캐스트 빅보이 & J.Y. Park ″The Asian Soul″)",
    playlists: [playlists[6]],
  },
  {
    videoId: "XgbrZZB9Ya0",
    artist: "씨야",
    title: "사랑하기 때문에",
    playlists: [playlists[6]],
  },
  {
    videoId: "_MythyZ0w3s",
    artist: "씨야",
    title: "미친 사랑의 노래",
    playlists: [playlists[6]],
  },
  {
    videoId: "_zwA5jlgfmo",
    artist: "SG워너비",
    title: "한여름날의 꿈 (feat. 옥주현)",
    playlists: [playlists[6]],
  },
  {
    videoId: "_-7ophEQBN4",
    artist: "먼데이 키즈",
    title: "가슴으로 외쳐 (feat. Rhymer)",
    playlists: [playlists[6]],
  },
  {
    videoId: "BEK9vOGAqXM",
    artist: "먼데이 키즈",
    title: "발자국",
    playlists: [playlists[6]],
  },
  {
    videoId: "xmX5lqVBH1s",
    artist: "BIG Naughty",
    title: "Vancouver 2",
    playlists: [playlists[2], playlists[4], playlists[6], playlists[7]],
  },
  {
    videoId: "0bTCIbyvBBc",
    artist: "NELL",
    title: "기억을 걷는 시간",
    playlists: [playlists[6]],
  },
  {
    videoId: "6HLr5ghMG1c",
    artist: "제아 & 미료",
    title: "Love Is...",
    playlists: [playlists[6]],
  },
  {
    videoId: "Na7voCrpzF0",
    artist: "프라이머리",
    title: "씨시루 (feat. Zion.T, Gaeko)",
    playlists: [playlists[6]],
  },
  {
    videoId: "hQQyYLkqIIk",
    artist: "린",
    title: "오늘 밤 (feat. 배치기)",
    playlists: [playlists[6]],
  },
  {
    videoId: "nUxLhI8iOrc",
    artist: "긱스",
    title: "어때 (feat. 하림)",
    playlists: [playlists[6]],
  },
  {
    videoId: "xKZ3U8viuIU",
    artist: "아이유",
    title: "금요일에 만나요 (feat. 장이정)",
    playlists: [playlists[6]],
  },
  {
    videoId: "l0rcWimJmQ8",
    artist: "하이포 & 아이유",
    title: "봄 사랑 벚꽃 말고",
    playlists: [playlists[6]],
  },
  {
    videoId: "6yzwnte9rXc",
    artist: "Zion.T",
    title: "꺼내 먹어요",
    playlists: [playlists[6]],
  },
  {
    videoId: "PTIIlOr_C48",
    artist: "다비치",
    title: "두사랑 (feat. 매드클라운)",
    playlists: [playlists[6]],
  },
  {
    videoId: "IoqZ3tjbu40",
    artist: "M.C THE MAX",
    title: "그 남잔 말야",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "8diBGaW4Mh4",
    artist: "태양",
    title: "눈, 코, 입",
    playlists: [playlists[6]],
  },
  {
    videoId: "cQuqs2LrXbo",
    artist: "백예린",
    title: "우주를 건너",
    playlists: [playlists[6]],
  },
  {
    videoId: "Y4U1V-eCe5s",
    artist: "BTS",
    title: "봄날",
    playlists: [playlists[6]],
  },
  {
    videoId: "ixkBzA94y0M",
    artist: "박재범",
    title: "All I Wanna Do (feat. Hoody, Loco)",
    playlists: [playlists[6]],
  },
  {
    videoId: "PjrvwPPY-O8",
    artist: "소나기",
    title: "용준형 (feat. 10cm)",
    playlists: [playlists[5], playlists[6]],
  },
  {
    videoId: "uw_HR9jIJww",
    artist: "헤이즈",
    title: "Jenga (feat. Gaeko)",
    playlists: [playlists[6]],
  },
  {
    videoId: "7eOmBC9sUPM",
    artist: "펀치",
    title: "밤이 되니까",
    playlists: [playlists[6]],
  },
  {
    videoId: "7vEe8dLW7WM",
    artist: "펀치 & 김보경",
    title: "지금 술 한잔 했어",
    playlists: [playlists[6]],
  },
  {
    videoId: "m-xmTB12EqI",
    artist: "펀치 & 더원",
    title: "아프다니까",
    playlists: [playlists[6]],
  },
  {
    videoId: "AmdgIK8-raM",
    artist: "티아라",
    title: "TTL (Time To Love)",
    playlists: [playlists[6]],
  },
  {
    videoId: "H04mbKV44so",
    artist: "우원재",
    title: "시차 (feat. 로꼬, 그레이)",
    playlists: [playlists[6]],
  },
  {
    videoId: "BUzI-awsi1s",
    artist: "장범준",
    title: "노래방에서",
    playlists: [playlists[6]],
  },
  {
    videoId: "VpaUh_BGqE0",
    artist: "엔플라잉",
    title: "옥탑방",
    playlists: [playlists[6]],
  },
  {
    videoId: "eN4QuOaXUTs",
    artist: "이소라",
    title: "신청곡",
    playlists: [playlists[2], playlists[5], playlists[6], playlists[7]],
  },
  {
    videoId: "-t2BFc8QIrA",
    artist: "개리 & 정인",
    title: "사람냄새",
    playlists: [playlists[6]],
  },
  {
    videoId: "IH728Tc9AX4",
    artist: "박명호",
    title: "울고 있는 너의 모습 보면 (feat. 류주환)",
    playlists: [
      playlists[1],
      playlists[2],
      playlists[5],
      playlists[6],
      playlists[7],
    ],
  },
  {
    videoId: "9FeqfatBxF8",
    artist: "박명호",
    title: "사진 (하늘만 바라봐) (feat. 류주환, Same Lee)",
    playlists: [
      playlists[1],
      playlists[2],
      playlists[5],
      playlists[6],
      playlists[7],
    ],
  },
  {
    videoId: "np42odaM8jw",
    artist: "드렁큰 타이거",
    title: "너희가 힙합을 아느냐?",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "1q_t6RNuH8c",
    artist: "폴킴",
    title: "모든 날, 모든 순간",
    playlists: [playlists[5], playlists[6]],
  },
  {
    videoId: "g7R8YphsB2Y",
    artist: "KozyPop",
    title: "파란색",
    playlists: [playlists[2], playlists[6], playlists[7]],
  },
  {
    videoId: "VPo5vrntXZs",
    artist: "싸이",
    title: "아름다운 이별 2 (feat. 이재훈)",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "IIMk6enNTmk",
    artist: "홍대광",
    title: "답이 없었어",
    playlists: [playlists[2], playlists[5], playlists[6], playlists[7]],
  },
  {
    videoId: "A4dbtFe6FsM",
    artist: "언터쳐블",
    title: "베인 (feat. Koonta of Rude Paper)",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "G9zL-A78oRg",
    artist: "프라이머리",
    title: "아끼지마 (feat. 초아, 아이언)",
    playlists: [playlists[6]],
  },
  {
    videoId: "Xq8-TO_YQdI",
    artist: "신승훈 & 에일리",
    title: "Fly Away",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "eHir_vB1RUI",
    artist: "태연",
    title: "Rain",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "lWDbSm4ExCw",
    artist: "NELL",
    title: "청춘연가",
    playlists: [playlists[2], playlists[5], playlists[6], playlists[7]],
  },

  {
    videoId: "mhnuvWRKLSo",
    artist: "먼데이 키즈",
    title: "흩어져",
    playlists: [playlists[6]],
  },
  {
    videoId: "qut_xT4unKs",
    artist: "먼데이 키즈",
    title: "입맞춤",
    playlists: [playlists[1], playlists[2], playlists[6], playlists[7]],
  },
  {
    videoId: "VRblIA3U_Y4",
    artist: "먼데이 키즈",
    title: "신기루",
    playlists: [
      playlists[1],
      playlists[2],
      playlists[5],
      playlists[6],
      playlists[7],
    ],
  },
  {
    videoId: "s1e3O1Cm5Gs",
    artist: "먼데이 키즈",
    title: "차가운 커피",
    playlists: [
      playlists[1],
      playlists[2],
      playlists[5],
      playlists[6],
      playlists[7],
    ],
  },
  {
    videoId: "j1twcJsU7Ww",
    artist: "먼데이 키즈",
    title: "고장난 열차",
    playlists: [
      playlists[1],
      playlists[2],
      playlists[5],
      playlists[6],
      playlists[7],
    ],
  },
  {
    videoId: "g3rD2V4meGs",
    artist: "이영지",
    title: "낮 밤",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "5eFYzh_YjLU",
    artist: "Supreme Team",
    title: "나만 모르게 (feat. T)",
    playlists: [playlists[1], playlists[2], playlists[6], playlists[7]],
  },
  {
    videoId: "5CMBNIAki88",
    artist: "이현우",
    title: "헤어진 다음날",
    playlists: [playlists[2], playlists[5], playlists[6], playlists[7]],
  },
  {
    videoId: "Ua-vVBfopHA",
    artist: "김동률",
    title: "기억의 습작",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "_G1cVDy0fTg",
    artist: "Duke & Jones, Louis Theroux",
    title: "Jiggle Jiggle",
    playlists: [playlists[2], playlists[4], playlists[6], playlists[7]],
  },
  {
    videoId: "2lODuVyCcgU",
    artist: "에이트",
    title: "잘가요 내사랑",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "4I5AQcafqhA",
    artist: "플라워",
    title: "Crying",
    playlists: [playlists[1], playlists[5], playlists[6]],
  },
  {
    videoId: "NcWPtW2lNoE",
    artist: "플라워",
    title: "For You",
    playlists: [
      playlists[1],
      playlists[2],
      playlists[4],
      playlists[6],
      playlists[7],
    ],
  },
  {
    videoId: "3fp9effzCTE",
    artist: "버즈",
    title: "1st",
    playlists: [playlists[6]],
  },
  {
    videoId: "-xvOv7yL10I",
    artist: "버즈",
    title: "Monologue",
    playlists: [playlists[6]],
  },
  {
    videoId: "eN99TCIdIt4",
    artist: "버즈",
    title: "약자의 눈물",
    playlists: [playlists[6]],
  },
  {
    videoId: "G4BuSPt9iNQ",
    artist: "SG 워너비",
    title: "Timeless",
    playlists: [playlists[1], playlists[2], playlists[6]],
  },
  {
    videoId: "Qpf26PtBXgo",
    artist: "소녀시대",
    title: "FOREVER 1",
    playlists: [playlists[6]],
  },
  {
    videoId: "MBSpoTozBdg",
    artist: "우디",
    title: "이 노래가 클럽에서 나온다면",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "ZgKExhAL7mE",
    artist: "라붐",
    title: "체온",
    playlists: [playlists[6]],
  },
  {
    videoId: "F01sUq_Rtds",
    artist: "YB",
    title: "박하사탕",
    playlists: [playlists[2], playlists[5], playlists[6], playlists[7]],
  },
  {
    videoId: "_tN91WXp5Rw",
    artist: "이수영",
    title: "얼마나 좋을까 (FINAL FANTASY-X OST)",
    playlists: [playlists[2], playlists[5], playlists[6], playlists[7]],
  },
  {
    videoId: "kXYiU_JCYtU",
    artist: "Linkin Park",
    title: "Numb",
    playlists: [playlists[2], playlists[4], playlists[6], playlists[7]],
  },
  {
    videoId: "8Irb9NEZkRM",
    artist: "10CM & BIG Naughty",
    title: "딱 10CM만",
    playlists: [playlists[6]],
  },
  {
    videoId: "lvwSKGIYoag",
    artist: "Brown Eyes",
    title: "점점",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "ok1782_PBaA",
    artist: "얀",
    title: "그래서 그대는",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "jpMoPG5W860",
    artist: "홍경민",
    title: "후",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "1Mb5b9J7xa0",
    artist: "조PD",
    title: "My Style",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "4oKDKl4IOM8",
    artist: "조PD",
    title: "Fever (feat. 이정현)",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "w7CBx-pSUbk",
    artist: "조PD",
    title: "보란듯이 (feat. 정슬기)",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "yfx8APtBmAU",
    artist: "MC 스나이퍼",
    title: "야간비행 (feat. Rachael Yamagata)",
    playlists: [
      playlists[2],
      playlists[4],
      playlists[5],
      playlists[6],
      playlists[7],
    ],
  },
  {
    videoId: "2A-PEGmBC48",
    artist: "MC 스나이퍼",
    title: "사랑비극 Part.1 (feat. 김신의)",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "4yKNsJWXwTI",
    artist: "그루비룸",
    title: "행성 (feat. Blue.D, Jhnovr)",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "Hrb9jpU_IdU",
    artist: "첸 & 헤이즈 & 바이브",
    title: "썸타",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "qNZ3A39m9c8",
    artist: "신용재",
    title: "가수가 된 이유",
    playlists: [playlists[6]],
  },
  {
    videoId: "X8mRqGRJeDw",
    artist: "동방신기",
    title: "주문",
    playlists: [
      playlists[2],
      playlists[3],
      playlists[4],
      playlists[6],
      playlists[7],
    ],
  },

  {
    videoId: "IBuyFRtW2sg",
    artist: "요조 & 김진표",
    title: "좋아해",
    playlists: [
      playlists[2],
      playlists[4],
      playlists[5],
      playlists[6],
      playlists[7],
    ],
  },
  {
    videoId: "Vo8Gh7IJjm4",
    artist: "김진표",
    title: "아직 못다한 이야기 (feat. BMK)",
    playlists: [playlists[2], playlists[6], playlists[7]],
  },
  {
    videoId: "J_f-QJJuZ-U",
    artist: "김진표",
    title: "샴푸의 요정 (feat. 김조한, 이준)",
    playlists: [playlists[2], playlists[6], playlists[7]],
  },
  {
    videoId: "FDYgubT8iCI",
    artist: "김진표",
    title: "아무 말도 하지마 (feat. 케이윌)",
    playlists: [playlists[6]],
  },
  {
    videoId: "Wp4do3WlQkk",
    artist: "김진표",
    title: "시간을 찾아서 (feat. 이적)",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "OXICsmyfVos",
    artist: "김진표",
    title: "영원토록 (feat. 존박)",
    playlists: [playlists[6]],
  },
  {
    videoId: "VuknJzeqXZM",
    artist: "태양",
    title: "I Need a Girl",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "Wl84Xsbu5cI",
    artist: "김건모",
    title: "미안해요",
    playlists: [playlists[1], playlists[2], playlists[6]],
  },
  {
    videoId: "615swCopnhs",
    artist: "거미",
    title: "날 그만 잊어요",
    playlists: [playlists[6]],
  },
  {
    videoId: "K3Bq9mIHbzw",
    artist: "거미",
    title: "친구라도 될 걸 그랬어",
    playlists: [playlists[6]],
  },
  {
    videoId: "wpywf5nZYLU",
    artist: "거미",
    title: "그대 돌아오면",
    playlists: [playlists[5], playlists[6]],
  },
  {
    videoId: "eNlOJ97LLPs",
    artist: "거미",
    title: "어른아이",
    playlists: [playlists[6]],
  },
  {
    videoId: "4duD8KFRUC8",
    artist: "거미",
    title: "기억상실",
    playlists: [playlists[6]],
  },
  {
    videoId: "Tgmet1-9B-A",
    artist: "거미",
    title: "미안해요 (feat. T.O.P)",
    playlists: [playlists[6]],
  },
  {
    videoId: "9k8FNMPax50",
    artist: "거미",
    title: "Because of You",
    playlists: [playlists[6]],
  },
  {
    videoId: "7drhVxWUDLA",
    artist: "거미",
    title: "남자라서",
    playlists: [playlists[6]],
  },
  {
    videoId: "o0kIUQlqOec",
    artist: "거미",
    title: "사랑은 없다",
    playlists: [playlists[6]],
  },
  {
    videoId: "9SsKw53K8Gg",
    artist: "거미",
    title: "내 생각날 거야",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "B5ngr-9yAJc",
    artist: "거미",
    title: "거울을 보다가",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "0LcN5gIE_TA",
    artist: "거미",
    title: "그만 헤어져",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "TKuArLs00bU",
    artist: "거미",
    title: "헤어진 다음 날 (feat. P-Type)",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "biy2PJBZuYI",
    artist: "거미",
    title: "누구세요",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "OUQ2wAJZ5aY",
    artist: "거미 & 바비킴",
    title: "러브 레시피",
    playlists: [playlists[6]],
  },
  {
    videoId: "BmcP7x99LDk",
    artist: "플라워",
    title: "Endless",
    playlists: [playlists[1], playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "I7EwLNhPgpg",
    artist: "헤이즈",
    title: "돌아오지마 (feat. 용준형)",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "rCeM57e2BfU",
    artist: "헤이즈",
    title: "And July (feat. DEAN, DJ Friz)",
    playlists: [playlists[6]],
  },
  {
    videoId: "eelfrHtmk68",
    artist: "Dean",
    title: "D",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "kEuc2w2HVhY",
    artist: "다이나믹 듀오",
    title: "Ring My Bell (feat. 나얼)",
    playlists: [playlists[3], playlists[4], playlists[6], playlists[7]],
  },
  {
    videoId: "UEbPNjL22gE",
    artist: "다이나믹 듀오",
    title: "불면증 (feat. Bobby Kim)",
    playlists: [playlists[2], playlists[5], playlists[6], playlists[7]],
  },
  {
    videoId: "2lwNO6YTADA",
    artist: "다이나믹 듀오",
    title: "날개뼈 (feat. 효린)",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "YjcU-0YEr54",
    artist: "윤미래",
    title: "Get It In (feat. Tiger JK, Jung In)",
    playlists: [playlists[3], playlists[6]],
  },
  {
    videoId: "XNQCyR8_2EQ",
    artist: "윤미래 (with JK, Bizzy)",
    title: "Angel",
    playlists: [playlists[6]],
  },
  {
    videoId: "kv88gSRnt-8",
    artist: "NELL",
    title: "백야",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "NwkNj56IaAw",
    artist: "NELL",
    title: "Ocean of Light",
    playlists: [playlists[2], playlists[4], playlists[6]],
  },
  {
    videoId: "XO92ZWK3j-s",
    artist: "NELL",
    title: "Stay",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "70WsITQrB24",
    artist: "NELL",
    title: "믿어선 안될 말",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "dNRwPsIBPLI",
    artist: "조장혁",
    title: "중독된 사랑",
    playlists: [playlists[1], playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "2pN87QdvMaM",
    artist: "이적",
    title: "하늘을 달리다",
    playlists: [playlists[6]],
  },
  {
    videoId: "1zTZtz_EeU0",
    artist: "이적",
    title: "그땐 미처 알지 못했지",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "WzRpXpkHv00",
    artist: "서태지",
    title: "울트라맨이야",
    playlists: [playlists[4]],
  },
  {
    videoId: "sVo6NWwK_o",
    artist: "Brown Eyes",
    title: "벌써 일년",
    playlists: [playlists[1], playlists[2], playlists[6]],
  },
  {
    videoId: "_2zMo-Rhk54",
    artist: "Brown Eyes",
    title: "With Coffee",
    playlists: [playlists[1], playlists[2], playlists[6], playlists[7]],
  },
  {
    videoId: "cJ7KKa6sj4E",
    artist: "노을",
    title: "붙잡고도",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "tKv1E7ITA3c",
    artist: "빅마마",
    title: "Break Away",
    playlists: [playlists[1], playlists[2], playlists[6]],
  },
  {
    videoId: "HwNxxRBobFE",
    artist: "YB",
    title: "잊을께",
    playlists: [playlists[6]],
  },
  {
    videoId: "BY4sHNaV4WU",
    artist: "박효신",
    title: "눈의 꽃",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "RNEAR251EKo",
    artist: "M.C THE MAX",
    title: "사랑의 시",
    playlists: [playlists[1], playlists[5], playlists[6]],
  },
  {
    videoId: "nKFVcpurV54",
    artist: "M.C THE MAX",
    title: "그대는 눈물겹다",
    playlists: [playlists[1], playlists[5], playlists[6]],
  },
  {
    videoId: "CvaB_UaBHR0",
    artist: "이수영",
    title: "휠릴리",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "1ZITc5a3isE",
    artist: "주석",
    title: "정상을 향한 독주 2",
    playlists: [playlists[1], playlists[4], playlists[6]],
  },
  {
    videoId: "upA01bvUemQ",
    artist: "나얼",
    title: "귀로",
    playlists: [playlists[1], playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "1-Lm2LUR8Ss",
    artist: "버즈",
    title: "가시",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "G7eLG4Tnc9c",
    artist: "버즈",
    title: "겁쟁이",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "OnO92YGNwD8",
    artist: "BMK",
    title: "꽃피는 봄이 오면",
    playlists: [playlists[1], playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "KeMbLY7ztDw",
    artist: "윤도현",
    title: "사랑했나봐",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "djp8SviCHGY",
    artist: "김건모",
    title: "서울의 달",
    playlists: [playlists[1], playlists[5], playlists[6]],
  },
  {
    videoId: "QK-Z1K67uaA",
    artist: "Sting",
    title: "Shape of My Heart",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "aevPTbhFrT8",
    artist: "언터쳐블",
    title: "Tell My Why (feat. Hwayoung)",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "MjHDcR-gkJE",
    artist: "드림캐쳐",
    title: "Full Moon",
    playlists: [playlists[6]],
  },
  {
    videoId: "I5_BQAtwHws",
    artist: "드림캐쳐",
    title: "YOU AND I",
    playlists: [playlists[6]],
  },
  {
    videoId: "nqC4uQKAa9A",
    artist: "Supreme Team",
    title: "그땐 그땐 그땐",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "CMFRR5n_yyc",
    artist: "Supreme Team",
    title: "왜",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "pLDXOebjblk",
    artist: "Supreme Team",
    title: "너 때문이야 (feat. 소울맨)",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "DLtd1SFCO6c",
    artist: "머생",
    title: "동그랗고 하얀 (feat. 송석준)",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "lPe0RlZ06RE",
    artist: "Due (feat. Miri)",
    title: "Hotclip",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "SpO83duj5wQ",
    artist: "Supreme Team",
    title: "배가 불렀지 (feat. 개코)",
    playlists: [
      playlists[1],
      playlists[2],
      playlists[5],
      playlists[6],
      playlists[7],
    ],
  },
  {
    videoId: "qmkodlvhCSE",
    artist: "O.O.O",
    title: "눈이 마주쳤을 때",
    playlists: [playlists[2], playlists[4], playlists[6], playlists[7]],
  },
  {
    videoId: "qD1kP_nJU3o",
    artist: "IVE",
    title: "WAVE",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "ukg1n_12BjM",
    artist: "업타운",
    title: "My Style",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "NcgEXwjAImo",
    artist: "Kim Petras",
    title: "Coconuts ",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "aNuwWB0SHUs",
    artist: "Stereo Hearts",
    title: "Glee Cast",
    playlists: [playlists[2], playlists[4], playlists[6], playlists[7]],
  },
  {
    videoId: "AM7rVkwiUIM",
    artist: "Young Cocoa",
    title: "Manila",
    playlists: [playlists[2], playlists[4], playlists[6], playlists[7]],
  },
  {
    videoId: "Ec7TN_11az8",
    artist: "The Kid LAROI & Justin Bieber",
    title: "Stay",
    playlists: [playlists[2], playlists[4], playlists[6], playlists[7]],
  },
  {
    videoId: "_h0hyT5Dkb8",
    artist: "Dead Man Walking",
    title: "City Wolf",
    playlists: [playlists[4], playlists[6], playlists[7]],
  },
  {
    videoId: "KmVSwFd3TCA",
    artist: "Bazzi",
    title: "Myself",
    playlists: [playlists[2], playlists[6], playlists[7]],
  },
  {
    videoId: "vcnfwop3PNc",
    artist: "DEAN",
    title: "21",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "uHaQrwrEXvE",
    artist: "COIN",
    title: "Brad Pitt ",
    playlists: [playlists[2], playlists[4], playlists[6], playlists[7]],
  },
  {
    videoId: "2akWL5BjykA",
    artist: "Brown Eyed Girls",
    title: "이별편지",
    playlists: [playlists[6]],
  },
  {
    videoId: "qhiZMJ_BYJI",
    artist: "SG워너비",
    title: "멋지게 이별",
    playlists: [playlists[1]],
  },
  {
    videoId: "EzQsoZYY470",
    artist: "JIDA",
    title: "Autumn Breeze (feat. Rachel Lim)",
    playlists: [playlists[2], playlists[5], playlists[6]],
  },
  {
    videoId: "tg6DGMhsj7Y",
    artist: "Taio Cruz",
    title: "She's Like A Star",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "crB9uNfyEMc",
    artist: "라임버스",
    title: "How Do You Want It (feat. 임정희)",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "LB3Lfs_bGqU",
    artist: "Brown Eyes",
    title: "언제나 그랬죠",
    playlists: [playlists[1], playlists[2], playlists[6]],
  },
  {
    videoId: "ICCgV4ZZEhE",
    artist: "박재범",
    title: "Nothin On You",
    playlists: [playlists[4], playlists[6]],
  },
  {
    videoId: "gBGvfnegBkM",
    artist: "정키 & 거미",
    title: "Without You",
    playlists: [playlists[2], playlists[6]],
  },
  {
    videoId: "6rj3h-cEqgg",
    artist: "소유 & 백현",
    title: "비가와",
    playlists: [playlists[2], playlists[5]],
  },
  {
    videoId: "mnpQsM-tqQU",
    artist: "윤하",
    title: "시간의 지평선",
    playlists: [playlists[7]],
  },
  {
    videoId: "A67RYFTImTQ",
    artist: "IVE",
    title: "Off The Record",
    playlists: [playlists[2], playlists[7]],
  },
  {
    videoId: "_pYY8p1gpmc",
    artist: "Barrie Gledden",
    title: "I Am The One",
    playlists: [playlists[3]],
  },
  {
    videoId: "_UkrDNugpXI",
    artist: "요아리",
    title: "TRUE",
    playlists: [playlists[2], playlists[7]],
  },
  {
    videoId: "ZlJNkflJjA4",
    artist: "IVE",
    title: "Mine",
    playlists: [playlists[2], playlists[7]],
  },
  {
    videoId: "sVbpvsrtTzM",
    artist: "크리스포터 & 청하",
    title: "When I Get Old",
    playlists: [playlists[2], playlists[7]],
  },
  {
    videoId: "dYIT_jeUBKg",
    artist: "프리스타일",
    title: "Y",
    playlists: [playlists[1]],
  },
  {
    videoId: "NIPtyAKxlRs",
    artist: "에픽하이",
    title: "우산 (feat. 윤하)",
    playlists: [playlists[1], playlists[5]],
  },
  {
    videoId: "xpHJnmp3Lyw",
    artist: "Gavy NJ",
    title: "해바라기",
    playlists: [playlists[1]],
  },

  {
    videoId: "eOqSUto9Z1g",
    artist: "Sweetbox",
    title: "Life Is Cool",
    playlists: [playlists[1]],
  },
  {
    videoId: "POApmDGm8r8",
    artist: "MC 스나이퍼",
    title: "마법의 성",
    playlists: [playlists[1]],
  },
  {
    videoId: "ppjRIEgcXIY",
    artist: "다이나믹 듀오",
    title: "죽일놈",
    playlists: [playlists[1]],
  },
  {
    videoId: "_TOu_1zVCUk",
    artist: "리쌍",
    title: "헤어지지 못하는 여자, 떠나가지 못하는 남자 (feat. 정인)",
    playlists: [playlists[1]],
  },
  {
    videoId: "uNgg_uBYZkw",
    artist: "Brown Eyed Girls",
    title: "LOVE",
    playlists: [playlists[1]],
  },
  {
    videoId: "VUhGP9sqKdw",
    artist: "원투",
    title: "못된여자 (feat. 서인영)",
    playlists: [playlists[1]],
  },
  {
    videoId: "z5_HPxLJBf0",
    artist: "원투",
    title: "못된여자2 (feat. 서인영)",
    playlists: [playlists[1]],
  },
  {
    videoId: "bv1PxDNQ6bo",
    artist: "허밍 어반 스테레오",
    title: "Hawaiian Couple",
    playlists: [playlists[1]],
  },
  {
    videoId: "faPQoNUC4GQ",
    artist: "자두",
    title: "대화가 필요해",
    playlists: [playlists[1]],
  },
  {
    videoId: "v3SaQZypZ_U",
    artist: "하울, 제이",
    title: "사랑인가요 (궁 OST)",
    playlists: [playlists[1]],
  },
  {
    videoId: "4mDOG3PAjao",
    artist: "샵",
    title: "내 입술... 따뜻한 커피처럼",
    playlists: [playlists[1]],
  },
  {
    videoId: "iaDgfQ0sIYY",
    artist: "싸이",
    title: "낙원 (feat. 이재훈)",
    playlists: [playlists[1]],
  },
  {
    videoId: "Cbg6nJulpEQ",
    artist: "이지라이프",
    title: "너말고 니언니",
    playlists: [playlists[1]],
  },
  {
    videoId: "oF7C6GuMD5g",
    artist: "Brown Eyed Girls",
    title: "Hold The Line (feat. 조PD)",
    playlists: [playlists[1], playlists[6]],
  },
  {
    videoId: "c9sEdAo39gk",
    artist: "언터쳐블",
    title: "가슴에 살아 (feat. 나르샤)",
    playlists: [playlists[1]],
  },
  {
    videoId: "c7KXtINADRo",
    artist: "박해경",
    title: "Lemon Tree",
    playlists: [playlists[1]],
  },
  {
    videoId: "sGD75Kncck8",
    artist: "PK헤만",
    title: "Evergreen (feat. 이지혜)",
    playlists: [playlists[1]],
  },
  {
    videoId: "fuCmW_1_wxs",
    artist: "더 넛츠",
    title: "사랑의 바보",
    playlists: [playlists[1]],
  },
  {
    videoId: "98Q2p-3kMDI",
    artist: "izi",
    title: "응급실",
    playlists: [playlists[1]],
  },
  {
    videoId: "fuFJqIfnB5o",
    artist: "버즈",
    title: "사랑은 가슴이 시킨다",
    playlists: [playlists[1]],
  },
  {
    videoId: "2lODuVyCcgU",
    artist: "에이트",
    title: "잘가요 내사랑",
    playlists: [playlists[1]],
  },
  {
    videoId: "zgvI5Jqph08",
    artist: "양정승",
    title: "밤하늘의 별을 (with KCM, No Noo)",
    playlists: [playlists[1]],
  },
  {
    videoId: "h0cj_A0np-M",
    artist: "버즈",
    title: "은인",
    playlists: [playlists[1]],
  },
  {
    videoId: "_6C5-abCx6g",
    artist: "윤하",
    title: "기다리다",
    playlists: [playlists[1]],
  },
  {
    videoId: "-VP7fUqTWYY",
    artist: "태연",
    title: "들리나요",
    playlists: [playlists[1]],
  },
  {
    videoId: "2WyOq7IMEnc",
    artist: "이보람",
    title: "처음 그 자리에",
    playlists: [playlists[1]],
  },
  {
    videoId: "oo0ESiTp6VM",
    artist: "유미",
    title: "별",
    playlists: [playlists[1]],
  },
  {
    videoId: "qmlUuTvKUpU",
    artist: "러브홀릭",
    title: "인형의 꿈",
    playlists: [playlists[1]],
  },
  {
    videoId: "acdAWdnSKmE",
    artist: "럼블피쉬",
    title: "비와 당신",
    playlists: [playlists[1]],
  },
  {
    videoId: "1RvuFAWlkdo",
    artist: "god",
    title: "길",
    playlists: [playlists[1]],
  },
  {
    videoId: "yPqI1VAHX8Q",
    artist: "모세",
    title: "사랑인걸",
    playlists: [playlists[1]],
  },
  {
    videoId: "JRF7F2E96uw",
    artist: "김형중",
    title: "그랬나봐",
    playlists: [playlists[1]],
  },
  {
    videoId: "oQjzTVCIK5A",
    artist: "쿨",
    title: "아로하",
    playlists: [playlists[1]],
  },
  {
    videoId: "0lgNwO6eUpY",
    artist: "Brown Eyed Soul",
    title: "My Story",
    playlists: [playlists[1]],
  },
  {
    videoId: "G6pMhSdv8Fg",
    artist: "테이",
    title: "같은 배게...",
    playlists: [playlists[1]],
  },
  {
    videoId: "q5mPn6__Brk",
    artist: "이기찬",
    title: "미인",
    playlists: [playlists[1]],
  },
  {
    videoId: "nD1p_H3qo_A",
    artist: "성시경",
    title: "희재",
    playlists: [playlists[1], playlists[5], playlists[6]],
  },
  {
    videoId: "gt7kce8hgSs",
    artist: "지아",
    title: "술 한잔 해요",
    playlists: [playlists[1]],
  },
  {
    videoId: "QeHrryN0zHo",
    artist: "테이",
    title: "사랑은...향기를 남기고",
    playlists: [playlists[1]],
  },
];
